# 服务器配置
server:
  address: 0.0.0.0 # IP访问地址
  port: 8080 # 端口
  servlet:
    context-path: /api # 访问路径开头
    # cookie 30 天过期
    session:
      cookie: # 自定义 cookie 属性
        max-age: 2592000 # 单位秒

spring:
  application:
    name: partner-matching-backend # 项目名称
  # 默认 dev 环境
  profiles:
    active: dev
  mvc:
    pathmatch:
      # 解决 Spring Boot 2.6.0 版本以上无法访问路径的问题（swagger2）
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # todo 请修改为自己的数据库地址, 端口(我这里使用了3305，默认3306），用户名，密码
    url: jdbc:mysql://localhost:3305/yupao?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    # todo 若你的 Redis 需要密码，请打开注释，并填写密码
    #    password: root
  # session 配置
  session:
    # todo 开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 统一配置返回时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

logging:
  file:
    # 日志文件路径,可以使用绝对路径和相对路径
    path: ${user.dir}/logs  # 当前项目根路径${user.dir}
    #path: E:/project_logs/partner-matching-backend # 绝对路径